- name: Create /data/containers/homeassistant/config
  file:
    path=/data/containers/homeassistant/config
    state=directory
    mode=0755
- name: Copy config YAML files
  copy:
    src={{ item }}
    dest=/data/containers/homeassistant/config
    owner=root
    group=root
    mode=0644
  with_fileglob:
    - ../../configs/*.yaml
  notify:
    - restart home assistant
- name: Copy secrets.yaml
  copy:
    src=../../../homeassistant-config-secrets/secrets.yaml
    dest=/data/containers/homeassistant/config/secrets.yaml
    owner=root
    group=root
    mode=0644
  notify:
    - restart home assistant
- name: Copy zones.yaml
  copy:
    src=../../../homeassistant-config-secrets/zones.yaml
    dest=/data/containers/homeassistant/config/zones.yaml
    owner=root
    group=root
    mode=0644
  notify:
    - restart home assistant

