- name: Create /etc/homeassistant/config
  file:
    path=/etc/homeassistant/config
    state=directory
    mode=0755
- name: Copy config YAML files
  copy:
    src={{ item }}
    dest=/etc/homeassistant/config
    owner=root
    group=root
    mode=0644
  with_fileglob:
    - ../../configs/*.yaml
- name: Copy secrets.yaml
  copy:
    src=../../../homeassistant-config-secrets/secrets.yaml
    dest=/etc/homeassistant/config/secrets.yaml
    owner=root
    group=root
    mode=0644
