-  alias: barn air compressor on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_air_compressor
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_air_compressor
-  alias: barn air compressor off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_air_compressor
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_air_compressor
-  alias: barn xmas lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_2
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_xmas_lights_1
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_xmas_lights_1
-  alias: barn xmas lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_2
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_xmas_lights_1
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_xmas_lights_1
-  alias: barn storage lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_3
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_lower_storage_lights
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_lower_storage_lights
-  alias: barn storage lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_3
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_lower_storage_lights
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_lower_storage_lights
-  alias: barn fluorescent lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_4
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_slide_fluorescent
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_slide_fluorescent
-  alias: barn fluorescent lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_4
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_slide_fluorescent
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_slide_fluorescent
-  alias: shed indoor lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.shed_inside_light_switch
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.shed_fluorescent_light_1
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.shed_fluorescent_light_1
-  alias: shed indoor lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.shed_inside_light_switch
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.shed_fluorescent_light_1
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.shed_fluorescent_light_1

-  alias: test lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.test_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.test_light_1
      state: 'off'
   action:
#    - service: notify.pushover
#      data:
#        message: "light toggled"
    - service: light.turn_on
      entity_id: light.test_light_1
-  alias: test lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.test_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.test_light_1
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.test_light_1
-  alias: workshop indoor lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.workshop_inside_light_switch
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.workshop_indoor_lights
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.workshop_indoor_lights
-  alias: workshop indoor lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.workshop_inside_light_switch
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.workshop_indoor_lights
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.workshop_indoor_lights
    - service: notify.slackbot
      data:
        message: ":bulb: Workshop lights switched off"
-  alias: workshop lights on when door opens
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.workshop_door_right
     from: 'on'
     to: 'off'
   condition:
      condition: state
      entity_id: light.workshop_indoor_lights
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.workshop_indoor_lights
- alias: notify workshop door right opened
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.workshop_door_right
   from: 'on'
   to: 'off'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Workshop right hand door opened"
- alias: noitfy workshop door left opened
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.workshop_door_left
   from: 'on'
   to: 'off'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Workshop left hand door opened"
- alias: notify workshop door right closed
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.workshop_door_right
   from: 'off'
   to: 'on'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Workshop right hand door closed"
- alias: noitfy workshop door left closed
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.workshop_door_left
   from: 'off'
   to: 'on'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Workshop left hand door closed"


# christmas lights on at night
- alias: barn xmas lights on at 4pm
  hide_entity: True
  trigger:
    platform: time
    hours: 16
    minutes: 0
    seconds: 0
  action:
   - service: light.turn_on
     entity_id: light.barn_xmas_lights_1
- alias: barn xmas lights off at 9pm
  hide_entity: True
  trigger:
    platform: time
    hours: 21
    minutes: 0
    seconds: 0
  action:
   - service: light.turn_off
     entity_id: light.barn_xmas_lights_1
# notify slack on incoming calls
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/incoming/prefilter
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Incoming phone call from {{ trigger.payload_json.from_display }} to {{ trigger.payload_json.to_display }}"
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/outgoing/dialing
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Outgoing phone call to {{ trigger.payload_json.to_display }}"
