# office
- alias: notify office door opened
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.office_door
   from: 'on'
   to: 'off'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Office door opened"
- alias: notify office door closed
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.office_door
   from: 'off'
   to: 'on'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Office door closed"

# notify slack on incoming calls
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/incoming/prefilter
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Incoming phone call from {{ trigger.payload_json.from_display }} to {{ trigger.payload_json.to_display }}"
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/outgoing/dialing
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Outgoing phone call to {{ trigger.payload_json.to_display }}"
