-  alias: barn air compressor on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_air_compressor
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_air_compressor
-  alias: barn air compressor off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_air_compressor
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_air_compressor
-  alias: barn xmas lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_2
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_xmas_lights_1
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_xmas_lights_1
-  alias: barn xmas lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_2
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_xmas_lights_1
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_xmas_lights_1
-  alias: barn storage lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_3
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_lower_storage_lights
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_lower_storage_lights
-  alias: barn storage lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_3
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_lower_storage_lights
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_lower_storage_lights
-  alias: barn fluorescent lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_4
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_slide_fluorescent
      state: 'off'
   action:
    - service: light.turn_on
      entity_id: light.barn_slide_fluorescent
-  alias: barn fluorescent lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.barn_inside_switch_4
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.barn_slide_fluorescent
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.barn_slide_fluorescent

-  alias: test lights on
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.test_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.test_light_1
      state: 'off'
   action:
#    - service: notify.pushover
#      data:
#        message: "light toggled"
    - service: light.turn_on
      entity_id: light.test_light_1
-  alias: test lights off
   hide_entity: True
   trigger:
     platform: state
     entity_id: binary_sensor.test_switch_1
     from: 'off'
     to: 'on'
   condition:
      condition: state
      entity_id: light.test_light_1
      state: 'on'
   action:
    - service: light.turn_off
      entity_id: light.test_light_1

# office
- alias: notify office door opened
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.office_door
   from: 'on'
   to: 'off'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Office door opened"
- alias: notify office door closed
  hide_entity: True
  trigger:
   platform: state
   entity_id: binary_sensor.office_door
   from: 'off'
   to: 'on'
  action:
  - service: notify.slackbot
    data:
      message: ":door: Office door closed"

# notify slack on incoming calls
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/incoming/prefilter
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Incoming phone call from {{ trigger.payload_json.from_display }} to {{ trigger.payload_json.to_display }}"
- alias: Notify incoming calls
  hide_entity: True
  trigger:
    platform: mqtt
    topic: phonecalls/home/outgoing/dialing
  action:
    - service: notify.slackbot
      data_template:
        message: ":phone: Outgoing phone call to {{ trigger.payload_json.to_display }}"
