- platform: generic
  name: Drive 1
  still_image_url: !secret cctv_drive1_still
  stream_source: !secret cctv_drive1_rtsp

- platform: generic
  name: Drive 2
  still_image_url: !secret cctv_drive2_still
  stream_source: !secret cctv_drive2_rtsp

- platform: generic
  name: Barn 1
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/301/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic

- platform: generic
  name: Barn 2
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/401/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic

- platform: generic
  name: Workshop 1
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/501/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic

- platform: generic
  name: Shed 1
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/601/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic

- platform: generic
  name: Woods 1
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/701/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic

- platform: generic
  name: Nursery
  still_image_url: http://cctvnvr1.home.nat.ms/ISAPI/Streaming/channels/801/picture
  username: !secret cctv_cctvnvr1_username
  password: !secret cctv_cctvnvr1_password
  authentication: basic
