- platform: mjpeg
  name: barnleft
  still_image_url: http://frigate1.home.nat.ms:5000/api/barnleft/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/barnleft

- platform: mjpeg
  name: barnright
  still_image_url: http://frigate1.home.nat.ms:5000/api/barnright/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/barnright

- platform: mjpeg
  name: bridge
  still_image_url: http://frigate1.home.nat.ms:5000/api/bridge/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/bridge

- platform: mjpeg
  name: driveeast
  still_image_url: http://frigate1.home.nat.ms:5000/api/driveeast/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/driveeast

- platform: mjpeg
  name: drivenorth
  still_image_url: http://frigate1.home.nat.ms:5000/api/drivenorth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/drivenorth

- platform: mjpeg
  name: drivewest
  still_image_url: http://frigate1.home.nat.ms:5000/api/drivewest/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/drivewest

- platform: mjpeg
  name: logsnorth
  still_image_url: http://frigate1.home.nat.ms:5000/api/logsnorth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/logsnorth

- platform: mjpeg
  name: logssouth
  still_image_url: http://frigate1.home.nat.ms:5000/api/logssouth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/logssouth

- platform: mjpeg
  name: pole
  still_image_url: http://frigate1.home.nat.ms:5000/api/pole/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/pole

- platform: mjpeg
  name: rear
  still_image_url: http://frigate1.home.nat.ms:5000/api/rear/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/rear

- platform: mjpeg
  name: shed
  still_image_url: http://frigate1.home.nat.ms:5000/api/shed/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/shed

- platform: mjpeg
  name: utility
  still_image_url: http://frigate1.home.nat.ms:5000/api/utility/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/utility

- platform: mjpeg
  name: workshop
  still_image_url: http://frigate1.home.nat.ms:5000/api/workshop/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/api/workshop
