- platform: mjpeg
  name: barnleft
  still_image_url: http://frigate1.home.nat.ms:5000/barnleft/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/barnleft

- platform: mjpeg
  name: barnright
  still_image_url: http://frigate1.home.nat.ms:5000/barnright/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/barnright

- platform: mjpeg
  name: bridge
  still_image_url: http://frigate1.home.nat.ms:5000/bridge/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/bridge

- platform: mjpeg
  name: driveeast
  still_image_url: http://frigate1.home.nat.ms:5000/driveeast/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/driveeast

- platform: mjpeg
  name: drivenorth
  still_image_url: http://frigate1.home.nat.ms:5000/drivenorth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/drivenorth

- platform: mjpeg
  name: drivewest
  still_image_url: http://frigate1.home.nat.ms:5000/drivewest/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/drivewest

- platform: mjpeg
  name: logsnorth
  still_image_url: http://frigate1.home.nat.ms:5000/logsnorth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/logsnorth

- platform: mjpeg
  name: logssouth
  still_image_url: http://frigate1.home.nat.ms:5000/logssouth/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/logssouth

- platform: mjpeg
  name: pole
  still_image_url: http://frigate1.home.nat.ms:5000/pole/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/pole

- platform: mjpeg
  name: rear
  still_image_url: http://frigate1.home.nat.ms:5000/rear/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/rear

- platform: mjpeg
  name: shed
  still_image_url: http://frigate1.home.nat.ms:5000/shed/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/shed

- platform: mjpeg
  name: utility
  still_image_url: http://frigate1.home.nat.ms:5000/utility/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/utility

- platform: mjpeg
  name: workshop
  still_image_url: http://frigate1.home.nat.ms:5000/workshop/latest.jpg
  mjpeg_url: http://frigate1.home.nat.ms:5000/workshop
