homeassistant:
  name: Llwyn-y-Gorras
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
#   - type: trusted_networks

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.17.0.1
    - 10.76.50.16

mobile_app:

cloud:
  alexa:
    filter:
      exclude_domains:
        - group

config:

recorder:
  purge_keep_days: 14

sensor: !include sensors.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

frontend:
history:
logbook:
  exclude:
    entities:
      - sensor.date_time
      - sensor.logstore_uptime
      - sensor.sethbed_uptime
      - sun.sun

updater:
sun:
conversation:

camera: !include cameras.yaml

cover: !include cover.yaml

light: !include lights.yaml

binary_sensor: !include binary_sensors.yaml

group: !include groups.yaml

automation: !include automation.yaml

scene: !include scenes.yaml

zones: !include zones.yaml

modbus: !include modbus.yaml

notify:
  - name: slackbot
    platform: slack
    api_key: !secret slackbot_ha_api_key
    default_channel: '#general'

# climate:
#  platform: honeywell
#  username: !secret evohome_username
#  password: !secret evohome_password

stream:

system_health:

switch: !include switches.yaml

script: !include scripts.yaml

ios:

influxdb:
    api_version: 2
    ssl: false
    host: !secret influxdb_host
    port: 8086
    token: !secret influxdb_token
    organization: !secret influxdb_org
    bucket: !secret influxdb_bucket
    max_retries: 3
    default_measurement: state
