homeassistant:
  name: Llwyn-y-Gorras
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
#   - type: trusted_networks

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.17.0.1
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 193.47.147.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

cloud:

config:

recorder:
  purge_keep_days: 14

sensor: !include sensors.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

frontend:
history:
logbook:
updater:
sun:
conversation:

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    site_id: !secret unifi_site
    ssid_filter:
      - 'LYG Home'

camera: !include cameras.yaml

light: !include lights.yaml

binary_sensor: !include binary_sensors.yaml

group: !include groups.yaml

automation: !include automation.yaml

scene: !include scenes.yaml

notify:
  - name: slackbot
    platform: slack
    api_key: !secret slackbot_ha_api_key
    default_channel: '#general'

# climate:
#  platform: honeywell
#  username: !secret evohome_username
#  password: !secret evohome_password

stream:

tplink:
  discovery: false
  switch:
    - host: 193.47.147.208
    - host: 193.47.147.213
    - host: 193.47.147.215
    - host: 193.47.147.233

fastdotcom:
  scan_interval:
      minutes: 30

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

system_health:

switch: !include switches.yaml
