homeassistant:
  name: Llwyn-y-Gorras
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: 3
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

sensor: !include sensors.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

frontend:
history:
logbook:
updater:
sun:
conversation:

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

camera: !include cameras.yaml

light: !include lights.yaml

binary_sensor: !include binary_sensors.yaml

group: !include groups.yaml

automation: !include automation.yaml

scene: !include scenes.yaml

notify:
  - name: slackbot
    platform: slack
    api_key: !secret slackbot_ha_api_key
    default_channel: '#general'

climate:
  platform: honeywell
  username: !secret evohome_username
  password: !secret evohome_password
