- platform: mqtt
  name: "Office window left"
  command_topic: "windows/office/left/command"
  state_topic: "windows/office/left/status"
  qos: 0
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "OPEN"
  state_closed: "CLOSED"
  optimistic: false
- platform: mqtt
  name: "Office window right"
  command_topic: "windows/office/right/command"
  state_topic: "windows/office/right/status"
  qos: 0
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "OPEN"
  state_closed: "CLOSED"
  optimistic: false
- platform: mqtt
  name: "Backbedroom window left"
  command_topic: "windows/backbedroom/left/command"
  state_topic: "windows/backbedroom/left/status"
  qos: 0
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "OPEN"
  state_closed: "CLOSED"
  optimistic: false
- platform: mqtt
  name: "Backbedroom window right"
  command_topic: "windows/backbedroom/right/command"
  state_topic: "windows/backbedroom/right/status"
  qos: 0
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "OPEN"
  state_closed: "CLOSED"
  optimistic: false
- platform: mqtt
  name: "Office blind left"
  payload_open: 100
  payload_close: 0
  command_topic: 'somfy/0x279623/level/cmd'
  position_topic: 'somfy/0x279623/level/set_state'
  set_position_topic: 'somfy/0x279623/level/cmd'
  state_open: 100g
  state_closed: 0
- platform: mqtt
  name: "Office blind right"
  payload_open: 100
  payload_close: 0
  command_topic: 'somfy/0x279624/level/cmd'
  position_topic: 'somfy/0x279624/level/set_state'
  set_position_topic: 'somfy/0x279624/level/cmd'
  state_open: 100
  state_closed: 0
- platform: mqtt
  name: "Backbedroom blind left"
  payload_open: 100
  payload_close: 0
  command_topic: 'somfy/0x279621/level/cmd'
  position_topic: 'somfy/0x279621/level/set_state'
  set_position_topic: 'somfy/0x279621/level/cmd'
  state_open: 100
  state_closed: 0
- platform: mqtt
  name: "Backbedroom blind right"
  payload_open: 100
  payload_close: 0
  command_topic: 'somfy/0x279622/level/cmd'
  position_topic: 'somfy/0x279622/level/set_state'
  set_position_topic: 'somfy/0x279622/level/cmd'
  state_open: 100
  state_closed: 0