- platform: mqtt
  name: "Window Dev"
  command_topic: "windows/office/left/command"
  state_topic: "windows/office/left/status"
  qos: 0
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "OPEN"
  state_opening: "OPENING"
  state_closed: "CLOSED"
  state_closing: "CLOSING"
  optimistic: false
  value_template: '{{ value.x }}'