# shed
    binary_sensor.shed_door:
      hidden: true
    sensor.shed_door_template:
      icon: mdi:door
    binary_sensor.shed_inside_light_switch:
      friendly_name: Light switch
    light.shed_led_flood_light_front:
      friendly_name: Flood front
    light.shed_led_flood_light_rear:
      friendly_name: Flood rear
    light.shed_led_flood_light_side:
      friendly_name: Flood side
    light.shed_fluorescent_light_1:
      friendly_name: Inside light
# workshop
    light.workshop_indoor_lights:
      friendly_name: Inside lights
    light.workshop_outdoor_flood:
      friendly_name: Outdoor flood
    binary_sensor.workshop_inside_light_switch:
      friendly_name: Inside light switch
    binary_sensor.workshop_outdoor_light_switch:
      friendly_name: Outdoor light switch
    sensor.workshop_door_left_template:
      friendly_name: Door left
      icon: mdi:door
    sensor.workshop_door_right_template:
      friendly_name: Door right
      icon: mdi:door
    binary_sensor.workshop_door_left:
      hidden: true
    binary_sensor.workshop_door_right:
      hidden: true
# barn
    binary_sensor.barn_inside_switch_1:
      friendly_name: Light switch 1
    binary_sensor.barn_inside_switch_2:
      friendly_name: Light switch 2
    binary_sensor.barn_inside_switch_3:
      friendly_name: Light switch 3
    binary_sensor.barn_inside_switch_4:
      friendly_name: Light switch 4
    light.barn_air_compressor:
      friendly_name: Air compressor
      icon: mdi:engine
    light.barn_lower_storage_lights:
      friendly_name: Left storage lights
    light.barn_slide_fluorescent:
      friendly_name: Right side light
    light.barn_festoon:
      friendly_name: Festoon
# office
    binary_sensor.office_door:
      hidden: true
    sensor.office_door_template:
      friendly_name: Door
      icon: mdi:glassdoor
# master bedroom
    sensor.bedroom_master_humidity:
      friendly_name: Humidity
    sensor.bedroom_master_temperature:
      friendly_name: Temperature
# Electricity
    sensor.currentcost_power:
        friendly_name: Supply
        icon: mdi:flash
# Telephones
    sensor.phone_last_incoming_call:
        friendly_name: Incoming
        icon: mdi:phone
    sensor.phone_last_rejected_call:
        friendly_name: Rejected
        icon: mdi:phone
    sensor.phone_last_outgoing_call:
        friendly_name: Outgoing
        icon: mdi:phone
# heating
    switch.heating_hot_water:
        friendly_name: Hot water
        icon: mdi:water-pump
    switch.heating_central_heating:
        friendly_name: Central heating
        icon: mdi:radiator

# misc items
    switch.lounge_lamp:
        friendly_name: Lounge lamp
        icon: mdi:lamp
    switch.temp1:
        friendly_name: Christmas tree
        icon: mdi:pine-tree

# garden
    switch.bridge_spotlights:
        friendly_name: Bridge lights
        icon: mdi:bridge
    switch.patio_festoon:
        friendly_name: Patio festoon
        icon: mdi:lightbulb
    switch.patio_fountain:
        friendly_name: Patio fountain
        icon: mdi:fountain

# irrigation
    switch.irrigation_a1:
        friendly_name: Irrigiation A1
        icon: mdi:flower
    switch.irrigation_a2:
        friendly_name: Irrigiation A2
        icon: mdi:flower
    switch.irrigation_a3:
        friendly_name: Irrigiation A3
        icon: mdi:flower
    switch.irrigation_a4:
        friendly_name: Irrigiation A4
        icon: mdi:flower
    switch.irrigation_b1:
        friendly_name: Irrigiation B1
        icon: mdi:flower
    switch.irrigation_b2:
        friendly_name: Irrigiation B2
        icon: mdi:flower
    switch.irrigation_b3:
        friendly_name: Irrigiation B3
        icon: mdi:flower
    switch.irrigation_b4:
        friendly_name: Irrigiation B4
        icon: mdi:flower
# sethbed
    switch.sethbed_local_control:
        friendly_name: Local control
        icon: mdi:hand
    switch.sethbed_output_led_power:
        friendly_name: LED Power
        icon: mdi:led-on
    switch.sethbed_output_led_1:
        friendly_name: LED 1
        icon: mdi:led-on
    switch.sethbed_output_led_2:
        friendly_name: LED 2
        icon: mdi:led-on
    switch.sethbed_output_led_3:
        friendly_name: LED 3
        icon: mdi:led-on

# interior lights
    switch.office_light:
      friendly_name: Office
      icon: mdi:lightbulb
    switch.downstairs_wc:
      friendly_name: Downstairs toilet
      icon: mdi:lightbulb
#    group.heating:
#        hidden: true
    sensor.nasdaq_nflx:
      friendly_name: Netflix
      icon: mdi:netflix
    script.sethbed_nightmode_toggle:
      friendly_name: Bed night mode
      icon: mdi:progress-clock
