# shed
    binary_sensor.shed_door:
      hidden: true
    sensor.shed_door_template:
      icon: mdi:glassdoor
    binary_sensor.shed_inside_light_switch:
      friendly_name: Light switch
    light.shed_led_flood_light_front:
      friendly_name: Flood front
    light.shed_led_flood_light_rear:
      friendly_name: Flood rear
    light.shed_led_flood_light_side:
      friendly_name: Flood side
    light.shed_fluorescent_light_1:
      friendly_name: Inside light
# workshop
    light.workshop_indoor_lights:
      friendly_name: Inside lights
    light.workshop_outdoor_flood:
      friendly_name: Outdoor flood
    binary_sensor.workshop_inside_light_switch:
      friendly_name: Inside light switch
    binary_sensor.workshop_outdoor_light_switch:
      friendly_name: Outdoor light switch
    sensor.workshop_door_left_template:
      friendly_name: Door left
      icon: mdi:glassdoor
    sensor.workshop_door_right_template:
      friendly_name: Door right
      icon: mdi:glassdoor
    binary_sensor.workshop_door_left:
      hidden: true
    binary_sensor.workshop_door_right:
      hidden: true
# barn
    binary_sensor.barn_inside_switch_1:
      friendly_name: Light switch 1
    binary_sensor.barn_inside_switch_2:
      friendly_name: Light switch 2
    binary_sensor.barn_inside_switch_3:
      friendly_name: Light switch 3
    binary_sensor.barn_inside_switch_4:
      friendly_name: Light switch 4
    light.barn_air_compressor:
      friendly_name: Air compressor
      icon: mdi:engine
    light.barn_lower_storage_lights:
      friendly_name: Left storage lights
    light.barn_slide_fluorescent:
      friendly_name: Right side light
    light.barn_xmas_lights_1:
      friendly_name: Christmas lights
# master bedroom
    sensor.bedroom_master_humidity:
      friendly_name: Humidity
    sensor.bedroom_master_temperature:
      friendly_name: Temperature
# internet
    sensor.wifi_clients:
        icon: mdi:wifi
    sensor.aaisp_el6a1_quota_remaining:
        friendly_name: FTTC 1 Remaining quota
        icon: mdi:chart-pie
    sensor.aaisp_el6a1_sync_down:
        friendly_name: FTTC 1 Sync down
        icon: mdi:arrow-down-bold
    sensor.aaisp_el6a1_sync_up:
        friendly_name: FTTC 1 Sync up
        icon: mdi:arrow-up-bold
    sensor.aaisp_el6a2_quota_remaining:
        friendly_name: FTTC 2 Remaining quota
        icon: mdi:chart-pie
    sensor.aaisp_el6a2_sync_down:
        friendly_name: FTTC 2 Sync down
        icon: mdi:arrow-down-bold
    sensor.aaisp_el6a2_sync_up:
        friendly_name: FTTC 2 Sync up
        icon: mdi:arrow-up-bold
# Electricity
    sensor.currentcost_power:
        friendly_name: Supply
        icon: mdi:flash
# Telephones
    sensor.phone_last_incoming_call:
        friendly_name: Incoming
        icon: mdi:phone
    sensor.phone_last_rejected_call:
        friendly_name: Rejected
        icon: mdi:phone
    sensor.phone_last_outgoing_call:
        friendly_name: Outgoing
        icon: mdi:phone

    group.heating:
        hidden: true
