
# views
default_view:
  name: Home
  view: yes
  entities:
     - group.heating
     - group.interiorlights
     - group.garden
     - group.irrigation
     - group.shed
     - group.barn
     - group.miscindoors
#    - group.bedroom_master
#    - group.shed
#    - group.barn
#    - group.workshop
#    - group.internet
indoors:
  name: Indoors
  view: yes
  entities:
    - group.heating
    - group.interiorlights
    - group.miscindoors
#    - group.climate
    - group.lounge
    - group.office
    - group.masterbedroom
    - group.sethbedroom
    - group.sethbed
outdoors:
  name: Outdoors
  view: yes
  entities:
    - group.garden
    - group.greenhouse
    - group.irrigation
    - group.shed
    - group.barn
cameras:
  name: Cameras
  view: yes
  entities:
    - camera.ch1
    - camera.ch2
    - camera.ch3
    - camera.ch5
    - camera.ch6
    - camera.ch7
    - camera.ch9
    - camera.ch10
    - camera.ch11
    - camera.ch12
    - camera.ch13
telecoms:
  name: Telecoms
  view: yes
  entities:
    - group.internet
    - group.phones
    - group.internet_ping_home
    - group.internet_ping_pembswifi
    - group.internet_ping_external
development:
  name: Dev
  view: yes
  entities:
    - group.relay_boards
    - group.test
    - group.location
    - group.weather
    - group.internet
#    - group.climate
    - group.electricity
    - group.phones
    - group.sethbed
    - group.quick_scenes
# groups
shed:
  name: Shed
  control: hidden
  entities:
    - light.shed_led_flood_light_front
    - light.shed_led_flood_light_rear
    - light.shed_led_flood_light_side
    - light.shed_fluorescent_light_1
    - sensor.shed_door_template
# shed disabled: binary_sensor.shed_inside_light_switch
barn:
  name: Barn and Workshop
  control: hidden
  entities:
    - light.barn_festoon
    - light.barn_lower_storage_lights
    - light.barn_slide_fluorescent
    - light.barn_air_compressor
    - light.workshop_indoor_lights
    - light.workshop_outdoor_flood
    - sensor.workshop_door_left_template
    - sensor.workshop_door_right_template
# barn disabled: binary_sensor.barn_inside_switch_1, binary_sensor.barn_inside_switch_2, binary_sensor.barn_inside_switch_3, binary_sensor.barn_inside_switch_4
# workshop disabled: binary_sensor.workshop_inside_light_switch, binary_sensor.workshop_outdoor_light_switch,
test: light.test_light_1, light.test_light_2, light.test_light_3, binary_sensor.test_switch_1, binary_sensor.test_door_1, sensor.pirelay3_version
relay_boards: sensor.pirelay1_version, sensor.pirelay2_version, sensor.pirelay3_version
internet:
  name: Internet
  control: hidden
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.speedtest_upload
    - sensor.fast_com_download
masterbedroom:
  name: Master bedroom
  control: hidden
  entities:
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity
    - sensor.master_bedroom_battery
lounge:
  name: Lounge
  control: hidden
  entities:
    - sensor.lounge_temperature
    - sensor.lounge_humidity
    - sensor.lounge_battery
    - switch.lounge_lamp
greenhouse:
  name: Greenhouse
  control: hidden
  entities:
    - sensor.greenhouse_temperature
    - sensor.greenhouse_humidity
    - sensor.greenhouse_battery
sethbedroom:
  name: Seth bedroom
  control: hidden
  entities:
    - sensor.seth_bedroom_temperature
    - sensor.seth_bedroom_humidity
    - sensor.seth_bedroom_battery
office:
  name: Office
  control: hidden
  entities:
    - sensor.office_door_template
    - switch.office_light
quick_scenes:
  name: Quick Scenes
  control: hidden
  entities:
    - scene.all_outdoor_lights_off
    - scene.outdoor_front_at_night
electricity:
  name: Electricity
  control: hidden
  entities:
    - sensor.currentcost_power
phones:
  name: Telephones
  control: hidden
  entities:
    - sensor.phone_last_incoming_call
    - sensor.phone_last_rejected_call
    - sensor.phone_last_outgoing_call
internet_ping_home:
  name: Ping home
  control: hidden
  entities:
    - binary_sensor.ping_rt1_home_nat_ms
internet_ping_pembswifi:
  name: Ping Pembs Wifi
  control: hidden
  entities:
    - binary_sensor.ping_pembswifi_ntp
    - binary_sensor.ping_pembswifi_resolver_1
    - binary_sensor.ping_pembswifi_resolver_2
internet_ping_external:
  name: Ping external
  control: hidden
  entities:
    - binary_sensor.ping_cloudflare_dns
    - binary_sensor.ping_google_dns
weather:
  name: Weather
  control: hidden
  entities:
    - sun.sun
    - sensor.yr_symbol
location:
  name: location
  control: hidden
  entities:
    - device_tracker.claires_iphone
    - device_tracker.nats_iphone
#climate:
#  name: Climate
#  entities:
#    - climate.guest_bed_1
#    - climate.hot_water
#    - climate.house
#    - climate.master_bed
#    - climate.nursery
#    - climate.office
interiorlights:
  name: Interior lights
  control: hidden
  entities:
    - switch.office_light
    - switch.downstairs_wc
sethbed:
  name: Seth bed
  control: hidden
  entities:
    - sensor.sethbed_uptime
    - sensor.sethbed_version
    - sensor.sethbed_temperature
    - sensor.sethbed_humidity
    - sensor.sethbed_playing
    - switch.sethbed_local_control
    - switch.sethbed_output_led_power
    - switch.sethbed_output_led_1
    - switch.sethbed_output_led_2
    - switch.sethbed_output_led_3
    - switch.sethbed_output_relay_1
    - switch.sethbed_output_relay_2
    - switch.sethbed_output_relay_3
    - switch.sethbed_output_relay_4
    - switch.sethbed_output_relay_5
    - switch.sethbed_output_relay_6
    - switch.sethbed_output_relay_7
    - switch.sethbed_output_relay_8
    - script.sethbed_service_reset
heating:
  name: Heating
  control: hidden
  entities:
    - switch.heating_hot_water
    - switch.heating_central_heating
garden:
  name: Garden
  control: hidden
  entities:
    - switch.bridge_spotlights
    - switch.patio_fountain
    - switch.patio_festoon
    - switch.mega_festoon
    - switch.logstore_indoor
    - switch.logstore_porch
    - switch.logstore_outside
    - light.flood_rgb1
    - light.flood_rgb2
miscindoors:
  name: Various items
  control: hidden
  entities:
     - switch.hair_straightners
irrigation:
  name: Irrigation
  control: hidden
  entities:
    - switch.irrigation_a1
    - switch.irrigation_a2
    - switch.irrigation_a3
    - switch.irrigation_a4
    - switch.irrigation_b1
    - switch.irrigation_b2
    - switch.irrigation_b3
    - switch.irrigation_b4
