
# views
default_view:
  view: yes
  entities:
     - group.heating
     - group.miscitems
     - group.shed
     - group.barn
     - group.workshop
     - group.quick_scenes
#    - group.bedroom_master
#    - group.shed
#    - group.barn
#    - group.workshop
#    - group.internet
indoors:
  name: Indoors
  view: yes
  entities:
    - group.bedroom_master
#    - group.climate
    - group.office
outdoors:
  name: Outdoors
  view: yes
  entities:
    - group.shed
    - group.barn
    - group.workshop
cameras:
  name: Cameras
  view: yes
  entities:
    - camera.Drive_1
    - camera.Drive_2
    - camera.Barn_1
    - camera.Barn_2
    - camera.Workshop_1
    - camera.Shed_1
    - camera.Woods_1
    - camera.Nursery
development:
  name: Dev
  view: yes
  entities:
    - group.relay_boards
    - group.test
    - group.location
    - group.weather
    - group.internet
#    - group.climate
    - group.electricity
    - group.phones
    - group.sethbed
# groups
shed: light.shed_led_flood_light_front, light.shed_led_flood_light_rear, light.shed_led_flood_light_side, light.shed_fluorescent_light_1, sensor.shed_door_template
# shed disabled: binary_sensor.shed_inside_light_switch
barn: light.barn_xmas_lights_1, light.barn_lower_storage_lights, light.barn_slide_fluorescent, light.barn_air_compressor
# barn disabled: binary_sensor.barn_inside_switch_1, binary_sensor.barn_inside_switch_2, binary_sensor.barn_inside_switch_3, binary_sensor.barn_inside_switch_4
workshop: light.workshop_indoor_lights, light.workshop_outdoor_flood, sensor.workshop_door_left_template, sensor.workshop_door_right_template
# workshop disabled: binary_sensor.workshop_inside_light_switch, binary_sensor.workshop_outdoor_light_switch,
test: light.test_light_1, light.test_light_2, light.test_light_3, binary_sensor.test_switch_1, binary_sensor.test_door_1, sensor.pirelay3_version
relay_boards: sensor.pirelay1_version, sensor.pirelay2_version, sensor.pirelay3_version
internet: sensor.speedtest_download, sensor.speedtest_ping, sensor.speedtest_upload, sensor.fastcom_download
bedroom_master:
  name: Master bedroom
  entities:
    - sensor.bedroom_master_humidity
    - sensor.bedroom_master_temperature
office:
  name: Office
  entities:
    - sensor.office_door_template
quick_scenes:
  name: Quick Scenes
  entities:
    - scene.all_outdoor_lights_off
    - scene.outdoor_front_at_night
electricity:
  name: Electricity
  entities:
    - sensor.currentcost_power
phones:
  name: Telephones
  entities:
    - sensor.phone_last_incoming_call
    - sensor.phone_last_rejected_call
    - sensor.phone_last_outgoing_call
weather:
  name: Weather
  entities:
    - sun.sun
    - sensor.yr_symbol
location:
  name: location
  entities:
    - device_tracker.nat6p_nat6p
    - device_tracker.natnexus6p_natnexua6p
    - device_tracker.natnexus6p_natnexus6p
#climate:
#  name: Climate
#  entities:
#    - climate.guest_bed_1
#    - climate.hot_water
#    - climate.house
#    - climate.master_bed
#    - climate.nursery
#    - climate.office
sethbed:
  name: Seth bed
  entities:
    - sensor.sethbed_uptime
    - sensor.sethbed_version
heating:
  name: Heating
  entities:
    - switch.heating_hot_water
    - switch.heating_central_heating
miscitems:
  name: Various items
  entities:
     - switch.bridge_lights
     - switch.hair_straightners
     - switch.lounge_lamp
     - switch.temp1
