# views
default_view:
  name: Home
  view: yes
  entities:
     - group.quickindoors
     - group.quickoutdoors
     - group.quickenvironment
     - camera.ch1
     - camera.ch9
quickindoors:
  name: Quick indoors
  control: hidden
  entities:
    - switch.sethbed_local_control
    - script.sethbed_nightmode_toggle
quickoutdoors:
  name: Quick outdoors
  control: hidden
  entities:
quickenvironment:
  name: Quick environment
  control: hidden
  entities:
    - switch.heating_hot_water
    - switch.heating_hot_water_immersion
    - switch.heating_central_heating
    - sensor.lounge_temperature
    - sensor.master_bedroom_temperature
    - sensor.seth_bedroom_temperature
indoors:
  name: Indoors
  view: yes
  entities:
    - group.heating
    - group.interiorlights
    - group.miscindoors
#    - group.climate
    - group.lounge
    - group.office
    - group.backbedroom
    - group.masterbedroom
    - group.sethbedroom
    - group.sethbed
outdoors:
  name: Outdoors
  view: yes
  entities:
    - group.garden
    - group.greenhouse
    - group.irrigation
    - group.shed
    - group.barn
cameras:
  name: Cameras
  view: yes
  entities:
    - camera.ch1
    - camera.ch2
    - camera.ch3
    - camera.ch5
    - camera.ch6
    - camera.ch7
    - camera.ch9
    - camera.ch10
    - camera.ch11
    - camera.ch12
    - camera.ch13
telecoms:
  name: Telecoms
  view: yes
  entities:
    - group.internet
    - group.phones
    - group.internet_ping_home
    - group.internet_ping_pembswifi
    - group.internet_ping_external
development:
  name: Dev
  view: yes
  entities:
    - group.devicesshelly
    - group.relay_boards
    - group.test
    - group.location
    - group.weather
    - group.internet
#    - group.climate
    - group.electricity
    - group.phones
    - group.sethbed
    - group.quick_scenes
    - group.iocontrollerdev
    - group.iocontrollercupboard1
    - group.iocontrollercupboard2
finance:
  name: Finance
  view: yes
  entities:
    - group.starlingjoint
    - group.starlingsavings
    - group.stockmarket
# groups
shed:
  name: Shed
  control: hidden
  entities:
    - light.shed_led_flood_light_front
    - light.shed_led_flood_light_rear
    - light.shed_led_flood_light_side
    - light.shed_fluorescent_light_1
    - sensor.shed_door_template
# shed disabled: binary_sensor.shed_inside_light_switch
barn:
  name: Barn and Workshop
  control: hidden
  entities:
    - light.barn_festoon
    - light.barn_lower_storage_lights
    - light.barn_slide_fluorescent
    - light.barn_air_compressor
    - light.workshop_indoor_lights
    - light.workshop_outdoor_flood
    - sensor.workshop_door_left_template
    - sensor.workshop_door_right_template
    - light.flood_rgb1
    - light.flood_rgb2
# barn disabled: binary_sensor.barn_inside_switch_1, binary_sensor.barn_inside_switch_2, binary_sensor.barn_inside_switch_3, binary_sensor.barn_inside_switch_4
# workshop disabled: binary_sensor.workshop_inside_light_switch, binary_sensor.workshop_outdoor_light_switch,
test: light.test_light_1, light.test_light_2, light.test_light_3, binary_sensor.test_switch_1, binary_sensor.test_door_1, sensor.pirelay3_version
relay_boards: sensor.pirelay1_version, sensor.pirelay2_version, sensor.pirelay3_version
internet:
  name: Internet
  control: hidden
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.speedtest_upload
    - sensor.fast_com_download
masterbedroom:
  name: Master bedroom
  control: hidden
  entities:
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity
lounge:
  name: Lounge
  control: hidden
  entities:
    - sensor.lounge_temperature
    - sensor.lounge_humidity
    - switch.hs100_3
    - switch.hs100_2
greenhouse:
  name: Greenhouse
  control: hidden
  entities:
    - sensor.greenhouse_temperature
    - sensor.greenhouse_humidity
sethbedroom:
  name: Seth bedroom
  control: hidden
  entities:
    - sensor.seth_bedroom_temperature
    - sensor.seth_bedroom_humidity
office:
  name: Office
  control: hidden
  entities:
    - sensor.office_door_template
    - switch.office_light
    - cover.office_window_left
    - cover.office_window_right
backbedroom:
  name: Back bedroom
  control: hidden
  entities:
    - cover.backbedroom_window_left
    - cover.backbedroom_window_right
quick_scenes:
  name: Quick Scenes
  control: hidden
  entities:
    - scene.all_outdoor_lights_off
    - scene.outdoor_front_at_night
electricity:
  name: Electricity
  control: hidden
  entities:
    - sensor.currentcost_power
phones:
  name: Telephones
  control: hidden
  entities:
    - sensor.phone_last_incoming_call
    - sensor.phone_last_rejected_call
    - sensor.phone_last_outgoing_call
internet_ping_home:
  name: Ping home
  control: hidden
  entities:
    - binary_sensor.ping_rt1_home_nat_ms
internet_ping_pembswifi:
  name: Ping Pembs Wifi
  control: hidden
  entities:
    - binary_sensor.ping_pembswifi_ntp
    - binary_sensor.ping_pembswifi_resolver_1
    - binary_sensor.ping_pembswifi_resolver_2
internet_ping_external:
  name: Ping external
  control: hidden
  entities:
    - binary_sensor.ping_cloudflare_dns
    - binary_sensor.ping_google_dns
weather:
  name: Weather
  control: hidden
  entities:
    - sensor.dark_sky_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_precip
    - sun.sun
    - sensor.yr_symbol
location:
  name: location
  control: hidden
  entities:
    - device_tracker.claires_iphone
    - device_tracker.nats_iphone
#climate:
#  name: Climate
#  entities:
#    - climate.guest_bed_1
#    - climate.hot_water
#    - climate.house
#    - climate.master_bed
#    - climate.nursery
#    - climate.office
interiorlights:
  name: Interior lights
  control: hidden
  entities:
    - switch.office_light
    - switch.downstairs_wc
sethbed:
  name: Seth bed
  control: hidden
  entities:
    - sensor.sethbed_uptime
    - sensor.sethbed_version
    - sensor.sethbed_temperature
    - sensor.sethbed_humidity
    - sensor.sethbed_playing
    - switch.sethbed_local_control
    - switch.sethbed_output_led_power
    - switch.sethbed_output_led_1
    - switch.sethbed_output_led_2
    - switch.sethbed_output_led_3
    - switch.sethbed_output_relay_1
    - switch.sethbed_output_relay_2
    - switch.sethbed_output_relay_3
    - switch.sethbed_output_relay_4
    - switch.sethbed_output_relay_5
    - switch.sethbed_output_relay_6
    - switch.sethbed_output_relay_7
    - switch.sethbed_output_relay_8
    - script.sethbed_service_reset
    - script.sethbed_nightmode_toggle
heating:
  name: Heating
  control: hidden
  entities:
    - switch.heating_hot_water
    - switch.heating_hot_water_immersion
    - switch.heating_central_heating
garden:
  name: Garden
  control: hidden
  entities:
    - switch.bridge_spotlights
    - switch.patio_fountain
    - switch.patio_festoon
    - switch.logstore_indoor
    - switch.logstore_porch
    - switch.logstore_outside
miscindoors:
  name: Various items
  control: hidden
  entities:
     - switch.hs100_1
     - switch.hs100_4
irrigation:
  name: Irrigation
  control: hidden
  entities:
    - switch.irrigation_a1
    - switch.irrigation_a2
    - switch.irrigation_a3
    - switch.irrigation_a4
    - switch.irrigation_b1
    - switch.irrigation_b2
    - switch.irrigation_b3
    - switch.irrigation_b4
devicesshelly:
  name: Shelly devices
  control: hidden
  entities:
    - sensor.lounge_battery
    - sensor.master_bedroom_battery
    - sensor.seth_bedroom_battery
    - sensor.greenhouse_battery
starlingjoint:
    name: Starling joint account
    control: hidden
    entities:
    - sensor.starling_joint_lastevent_description
    - sensor.starling_joint_balance_available
    - sensor.starling_joint_balance_amount
    - sensor.starling_joint_balance_cleared
    - sensor.starling_joint_balance_effective
    - sensor.starling_joint_balance_pending
starlingsavings:
    name: Starling savings
    control: hidden
    entities:
      - sensor.starling_goal_total_saved
      - sensor.starling_goal_total_target
      - sensor.starling_goal_total_percentage
      - sensor.starling_goal_roundup
stockmarket:
    name: Market
    control: hidden
    entities:
      - sensor.nasdaq_nflx
iocontrollerdev:
    name: IOController development dev1
    control: hidden
    entities:
      - sensor.iocontroller_dev1_connection
      - switch.iocontroller_dev1_do1
      - switch.iocontroller_dev1_do2
      - switch.iocontroller_dev1_do3
      - switch.iocontroller_dev1_do4
      - switch.iocontroller_dev1_do5
      - switch.iocontroller_dev1_do6
      - switch.iocontroller_dev1_do7
      - switch.iocontroller_dev1_do8
      - sensor.iocontroller_dev1_di1
      - sensor.iocontroller_dev1_di2
      - sensor.iocontroller_dev1_di3
      - sensor.iocontroller_dev1_di4
      - sensor.iocontroller_dev1_di5
      - sensor.iocontroller_dev1_di6
      - sensor.iocontroller_dev1_di7
      - sensor.iocontroller_dev1_di8
iocontrollercupboard1:
    name: IOController cupboard1
    control: hidden
    entities:
      - sensor.iocontroller_cupboard1_connection
      - switch.iocontroller_cupboard1_do1
      - switch.iocontroller_cupboard1_do2
      - switch.iocontroller_cupboard1_do3
      - switch.iocontroller_cupboard1_do4
      - switch.iocontroller_cupboard1_do5
      - switch.iocontroller_cupboard1_do6
      - switch.iocontroller_cupboard1_do7
      - switch.iocontroller_cupboard1_do8
      - sensor.iocontroller_cupboard1_di1
      - sensor.iocontroller_cupboard1_di2
      - sensor.iocontroller_cupboard1_di3
      - sensor.iocontroller_cupboard1_di4
      - sensor.iocontroller_cupboard1_di5
      - sensor.iocontroller_cupboard1_di6
      - sensor.iocontroller_cupboard1_di7
      - sensor.iocontroller_cupboard1_di8
iocontrollercupboard2:
    name: IOController cupboard2
    control: hidden
    entities:
      - sensor.iocontroller_cupboard2_connection
      - switch.iocontroller_cupboard2_do1
      - switch.iocontroller_cupboard2_do2
      - switch.iocontroller_cupboard2_do3
      - switch.iocontroller_cupboard2_do4
      - switch.iocontroller_cupboard2_do5
      - switch.iocontroller_cupboard2_do6
      - switch.iocontroller_cupboard2_do7
      - switch.iocontroller_cupboard2_do8
      - sensor.iocontroller_cupboard2_di1
      - sensor.iocontroller_cupboard2_di2
      - sensor.iocontroller_cupboard2_di3
      - sensor.iocontroller_cupboard2_di4
      - sensor.iocontroller_cupboard2_di5
      - sensor.iocontroller_cupboard2_di6
      - sensor.iocontroller_cupboard2_di7
      - sensor.iocontroller_cupboard2_di8