# views
default_view:
  view: yes
  entities:
     - group.climate
     - group.electricity
     - group.phones
     - group.quick_scenes
#    - group.bedroom_master
#    - group.shed
#    - group.barn
#    - group.workshop
#    - group.internet
indoors:
  name: Indoors
  view: yes
  entities:
    - group.bedroom_master
    - group.climate
outdoors:
  name: Outdoors
  view: yes
  entities:
    - group.shed
    - group.barn
    - group.workshop
cameras:
  name: Cameras
  view: yes
  entities:
    - camera.Drive_1
    - camera.Drive_2
    - camera.Barn_1
    - camera.Barn_2
    - camera.Workshop_1
    - camera.Shed_1
    - camera.Woods_1
development:
  name: Dev
  view: yes
  entities:
    - group.relay_boards
    - group.test
    - group.location
    - group.weather
    - group.internet
# groups
shed: light.shed_led_flood_light_front, light.shed_led_flood_light_rear, light.shed_led_flood_light_side, light.shed_fluorescent_light_1, binary_sensor.shed_inside_light_switch, sensor.shed_door_template
barn: light.barn_xmas_lights_1, light.barn_lower_storage_lights, light.barn_slide_fluorescent, light.barn_air_compressor, binary_sensor.barn_inside_switch_1, binary_sensor.barn_inside_switch_2, binary_sensor.barn_inside_switch_3, binary_sensor.barn_inside_switch_4
workshop: light.workshop_indoor_lights, light.workshop_outdoor_flood, binary_sensor.workshop_inside_light_switch, binary_sensor.workshop_outdoor_light_switch, sensor.workshop_door_left_template, sensor.workshop_door_right_template
test: light.test_light_1, light.test_light_2, light.test_light_3, binary_sensor.test_switch_1, binary_sensor.test_door_1, sensor.pirelay3_version
relay_boards: sensor.pirelay1_version, sensor.pirelay2_version, sensor.pirelay3_version
internet: sensor.wifi_clients, sensor.speedtest_download, sensor.speedtest_ping, sensor.speedtest_upload, sensor.fastcom_download, sensor.aaisp_el6a1_quota_remaining, sensor.aaisp_el6a2_quota_remaining, sensor.aaisp_el6a1_sync_down, sensor.aaisp_el6a1_sync_up, sensor.aaisp_el6a2_sync_down, sensor.aaisp_el6a2_sync_up
bedroom_master:
  name: Master bedroom
  entities:
    - sensor.bedroom_master_humidity
    - sensor.bedroom_master_temperature
quick_scenes:
  name: Quick Scenes
  entities:
    - scene.all_outdoor_lights_off
electricity:
  name: Electricity
  entities:
    - sensor.currentcost_power
phones:
  name: Telephones
  entities:
    - sensor.phone_last_incoming_call
    - sensor.phone_last_rejected_call
    - sensor.phone_last_outgoing_call
weather:
  name: Weather
  entities:
    - sun.sun
    - sensor.yr_symbol
location:
  name: location
  entities:
    - device_tracker.nat6p_nat6p
    - device_tracker.natnexus6p_natnexua6p
    - device_tracker.natnexus6p_natnexus6p
climate:
  name: Climate
  entities:
    - climate.guest_bed_1
    - climate.hot_water
    - climate.house
    - climate.master_bed
    - climate.nursery
    - climate.office
