- platform: mqtt
  schema: template
  name: "Workshop highbays"
  state_topic: "shelly4pm/workshop_4pm_1/status/switch:0"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/workshop_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'

- platform: mqtt
  schema: template
  name: "Workshop festoon"
  state_topic: "shelly4pm/workshop_4pm_1/status/switch:1"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/workshop_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": false}}'

- platform: mqtt
  schema: template
  name: "Workshop flood"
  state_topic: "shelly4pm/workshop_4pm_1/status/switch:2"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/workshop_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": false}}'

- platform: mqtt
  schema: template
  name: "Workshop heating"
  state_topic: "shelly4pm/workshop_4pm_1/status/switch:3"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/workshop_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn front highbays"
  state_topic: "shelly4pm/barn_4pm_1/status/switch:0"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn rear highbays"
  state_topic: "shelly4pm/barn_4pm_1/status/switch:1"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn understorage battens"
  state_topic: "shelly4pm/barn_4pm_1/status/switch:2"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn rear festoon"
  state_topic: "shelly4pm/barn_4pm_1/status/switch:3"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_1/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn seating fairy"
  state_topic: "shelly4pm/barn_4pm_2/status/switch:0"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_2/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn front flood left"
  state_topic: "shelly4pm/barn_4pm_2/status/switch:1"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_2/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 1, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn front festoon"
  state_topic: "shelly4pm/barn_4pm_2/status/switch:2"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_2/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 2, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn front flood right"
  state_topic: "shelly4pm/barn_4pm_2/status/switch:3"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_2/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 3, "on": false}}'

- platform: mqtt
  schema: template
  name: "Barn understorage fairy"
  state_topic: "shelly4pm/barn_4pm_3/status/switch:0"
  state_template: "{% if value_json.output %}on{% else %}off{% endif %}"
  command_topic: "shelly4pm/barn_4pm_3/rpc"
  command_on_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
  command_off_template: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'

- platform: mqtt
  name: "Workshop indoor lights"
  state_topic: "pirelay2/output1/status"
  command_topic: "pirelay2/output1/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Workshop outdoor flood"
  state_topic: "pirelay2/output2/status"
  command_topic: "pirelay2/output2/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Barn lower storage lights"
  state_topic: "pirelay2/output3/status"
  command_topic: "pirelay2/output3/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Barn slide fluorescent"
  state_topic: "pirelay2/output4/status"
  command_topic: "pirelay2/output4/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Barn festoon"
  state_topic: "pirelay2/output5/status"
  command_topic: "pirelay2/output5/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Barn air compressor"
  state_topic: "pirelay2/output6/status"
  command_topic: "pirelay2/output6/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Shed fluorescent light 1"
  state_topic: "pirelay1/output4/status"
  command_topic: "pirelay1/output4/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Shed LED flood light rear"
  state_topic: "pirelay1/output1/status"
  command_topic: "pirelay1/output1/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Shed LED flood light side"
  state_topic: "pirelay1/output2/status"
  command_topic: "pirelay1/output2/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Shed LED flood light front"
  state_topic: "pirelay1/output3/status"
  command_topic: "pirelay1/output3/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Test light 1"
  state_topic: "pirelay3/output1/status"
  command_topic: "pirelay3/output1/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Test light 2"
  state_topic: "pirelay3/output2/status"
  command_topic: "pirelay3/output2/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Test light 3"
  state_topic: "pirelay3/output3/status"
  command_topic: "pirelay3/output3/switch"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  schema: json
  name: flood rgb1
  state_topic: "rgblights/light1"
  command_topic: "rgblights/light1/set"
  brightness: true
  rgb: true

- platform: mqtt
  schema: json
  name: flood rgb2
  state_topic: "rgblights/light2"
  command_topic: "rgblights/light2/set"
  brightness: true
  rgb: true
