sethbed_service_reset:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'tractorbed/seth/service/cmnd/reset'
        payload: 'RESET'
sethbed_nightmode_toggle:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'tractorbed/seth/mode/nightmode'
        payload: 'TOGGLE'
outdoor_lighting_toggle:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'outdoorlighting/command'
        payload: 'TOGGLE'
barn_rollerdoor_toggle:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'shelly1/rollerdoor/cmnd/controller/POWER'
        payload: 'BLINK'

