- platform: darksky
  api_key: !secret darksky_api_key
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  monitored_conditions:
  - temperature
  - humidity
  - precip_probability
  - cloud_cover
- platform: mqtt
  name: pirelay1 version
  state_topic: "pirelay1/version"
- platform: mqtt
  name: pirelay2 version
  state_topic: "pirelay2/version"
- platform: mqtt
  name: pirelay3 version
  state_topic: "pirelay3/version"
- platform: mqtt
  name: greenhouse temperature
  unit_of_measurement: '°C'
  state_topic: shellies/shellyht-E01199/sensor/temperature
- platform: mqtt
  name: greenhouse humidity
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E01199/sensor/humidity
- platform: mqtt
  name: greenhouse battery
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E01199/sensor/battery
- platform: mqtt
  name: seth bedroom temperature
  unit_of_measurement: '°C'
  state_topic: shellies/shellyht-E005D9/sensor/temperature
- platform: mqtt
  name: seth bedroom humidity
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/humidity
- platform: mqtt
  name: seth bedroom battery
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/battery
- platform: template
  sensors:
    shed_door_template:
      value_template: '{% if is_state("binary_sensor.shed_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Door'
    workshop_door_left_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_left", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door left'
    workshop_door_right_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_right", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door right'
    office_door_template:
      value_template: '{% if is_state("binary_sensor.office_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Office door right'
# power usage
- platform: mqtt
  name: currentcost power
  unit_of_measurement: 'watts'
  state_topic: currentcost/currentcost/ch1/watts
# phones
- platform: mqtt
  name: phone last incoming call
  state_topic: phonecalls/home/incoming/prefilter
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last rejected call
  state_topic: phonecalls/home/incoming/rejected
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last outgoing call
  state_topic: phonecalls/home/outgoing/dialing
  value_template: '{{ value_json.to_display }} @ {{ value_json.when }}'
# time date
- platform: time_date
  display_options:
    - "date_time"
# seth bedroom
- platform: mqtt
  name: sethbed version
  state_topic: "tractorbed/seth/version"
- platform: mqtt
  name: sethbed uptime
  state_topic: "tractorbed/seth/uptime"
  value_template: '{{ (((value | int) / 60) | int) }}'
  unit_of_measurement: hours
- platform: mqtt
  name: sethbed playing
  state_topic: "tractorbed/seth/sound/playing"
- platform: mqtt
  name: sethbed temperature
  unit_of_measurement: '°C'
  state_topic: tractorbed/seth/temperature
  value_template: '{{ ((value | float) | round(2)) }}'
- platform: mqtt
  name: sethbed humidity
  unit_of_measurement: '%'
  state_topic: tractorbed/seth/humidity
  value_template: '{{ ((value | float) | round(2)) }}'
- platform: mqtt
  name: logstore uptime
  state_topic: logstore/tele/controller/STATE
  value_template: '{{ value_json.Uptime }}'
#
- platform: mqtt
  name: IOController dev1 DI1
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/1/status"
- platform: mqtt
  name: IOController dev1 DI2
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/2/status"
- platform: mqtt
  name: IOController dev1 DI3
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/3/status"
- platform: mqtt
  name: IOController dev1 DI4
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/4/status"
- platform: mqtt
  name: IOController dev1 DI5
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/5/status"
- platform: mqtt
  name: IOController dev1 DI6
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/6/status"
- platform: mqtt
  name: IOController dev1 DI7
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/7/status"
- platform: mqtt
  name: IOController dev1 DI8
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/8/status"
- platform: mqtt
  name: IOController dev1 connection
  state_topic: "iocontroller/dev/boards/dev1/connection"
- platform: mqtt
  name: IOController cupboard1 DI1
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/1/status"
- platform: mqtt
  name: IOController cupboard1 DI2
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/2/status"
- platform: mqtt
  name: IOController cupboard1 DI3
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/3/status"
- platform: mqtt
  name: IOController cupboard1 DI4
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/4/status"
- platform: mqtt
  name: IOController cupboard1 DI5
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/5/status"
- platform: mqtt
  name: IOController cupboard1 DI6
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/6/status"
- platform: mqtt
  name: IOController cupboard1 DI7
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/7/status"
- platform: mqtt
  name: IOController cupboard1 DI8
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/8/status"
- platform: mqtt
  name: IOController cupboard1 connection
  state_topic: "iocontroller/home/boards/cupboard1/connection"
- platform: mqtt
  name: IOController cupboard2 DI1
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/1/status"
- platform: mqtt
  name: IOController cupboard2 DI2
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/2/status"
- platform: mqtt
  name: IOController cupboard2 DI3
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/3/status"
- platform: mqtt
  name: IOController cupboard2 DI4
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/4/status"
- platform: mqtt
  name: IOController cupboard2 DI5
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/5/status"
- platform: mqtt
  name: IOController cupboard2 DI6
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/6/status"
- platform: mqtt
  name: IOController cupboard2 DI7
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/7/status"
- platform: mqtt
  name: IOController cupboard2 DI8
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/8/status"
- platform: mqtt
  name: IOController cupboard2 connection
  state_topic: "iocontroller/home/boards/cupboard2/connection"
- platform: mqtt
  name: downstairshallway temperature
  unit_of_measurement: '°C'
  state_topic: areas/downstairshallway/temperature/value
- platform: mqtt
  name: kitchen temperature
  unit_of_measurement: '°C'
  state_topic: areas/kitchen/temperature/value
- platform: mqtt
  name: lounge temperature
  unit_of_measurement: '°C'
  state_topic: areas/lounge/temperature/value
- platform: mqtt
  name: playroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/playroom/temperature/value
- platform: mqtt
  name: sauna temperature
  unit_of_measurement: '°C'
  state_topic: areas/sauna/temperature/value
- platform: mqtt
  name: utility temperature
  unit_of_measurement: '°C'
  state_topic: areas/utility/temperature/value
- platform: mqtt
  name: backbedroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/backbedroom/temperature/value
- platform: mqtt
  name: ensuite temperature
  unit_of_measurement: '°C'
  state_topic: areas/ensuite/temperature/value
- platform: mqtt
  name: mainlanding temperature
  unit_of_measurement: '°C'
  state_topic: areas/mainlanding/temperature/value
- platform: mqtt
  name: master bedroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/masterbedroom/temperature/value
- platform: mqtt
  name: office temperature
  unit_of_measurement: '°C'
  state_topic: areas/office/temperature/value
- platform: mqtt
  name: office landing temperature
  unit_of_measurement: '°C'
  state_topic: areas/officelanding/temperature/value
- platform: mqtt
  name: office wc temperature
  unit_of_measurement: '°C'
  state_topic: areas/officewc/temperature/value
# victron vebus
- platform: mqtt
  name: "victron vebus AC out power"
  state_topic: "victron/local/vebus/276/Ac/Out/P"
  unit_of_measurement: 'W'
  value_template: '{{ value_json.value }}'
- platform: mqtt
  name: "victron vebus AC out current"      
  state_topic: "victron/local/vebus/276/Ac/Out/L1/I"
  unit_of_measurement: 'A'
  value_template: '{{ value_json.value | int }}'

# AC IN
- platform: mqtt
  name: "victron vebus AC in current limit"
  state_topic: "victron/local/vebus/276/Ac/In/2/CurrentLimit"
  unit_of_measurement: 'A'
  value_template: '{{ value_json.value }}'
- platform: mqtt
  name: "victron vebus AC in current"
  state_topic: "victron/local/vebus/276/Ac/ActiveIn/L1/I"
  unit_of_measurement: 'A'
  value_template: '{{ value_json.value }}'
- platform: mqtt
  name: "victron vebus AC in power"
  state_topic: "victron/local/vebus/276/Ac/ActiveIn/L1/P"
  unit_of_measurement: 'W'
  value_template: '{{ value_json.value }}'

# Inverter state
- platform: mqtt
  name: "victron vebus mode"
  state_topic: "victron/local/vebus/276/Mode"
  value_template: '{{ value_json.value }}'
- platform: mqtt
  name: "victron vebus state"
  state_topic: "victron/local/vebus/276/State"
  value_template: '{{ value_json.value }}'

# victron solar
- platform: mqtt
  name: "victron solar current"
  state_topic: "victron/local/system/0/Dc/Pv/Current"
  unit_of_measurement: 'A'
  value_template: '{{ value_json.value | int }}'
- platform: mqtt
  name: "victron solar power"
  state_topic: "victron/local/system/0/Dc/Pv/Power"
  unit_of_measurement: 'W'
  value_template: '{{ value_json.value | int }}'


# victron battery
- platform: mqtt
  name: "victron battery soc"  
  state_topic: "victron/local/battery/512/Soc"
  unit_of_measurement: '%'  
  value_template: '{{ value_json.value }}'
- platform: mqtt
  name: "victron battery current"  
  state_topic: "victron/local/battery/512/Dc/0/Current"
  unit_of_measurement: 'A'  
  value_template: '{{ value_json.value | int }}'
- platform: mqtt
  name: "victron battery power"
  state_topic: "victron/local/battery/512/Dc/0/Power"
  unit_of_measurement: 'W'
  value_template: '{{ value_json.value | int }}'
- platform: mqtt
  name: "victron battery voltage"
  state_topic: "victron/local/battery/512/Dc/0/Voltage"
  unit_of_measurement: 'V'
  value_template: '{{ value_json.value | int }}'
