- platform: darksky
  api_key: !secret darksky_api_key
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  monitored_conditions:
  - temperature
  - temperature_max
  - temperature_min
  - humidity
  - precip_probability
  - cloud_cover
- platform: yr
- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload
  server_id: 16607
- platform: mqtt
  name: pirelay1 version
  state_topic: "pirelay1/version"
- platform: mqtt
  name: pirelay2 version
  state_topic: "pirelay2/version"
- platform: mqtt
  name: pirelay3 version
  state_topic: "pirelay3/version"
- platform: mqtt
  name: greenhouse temperature
  unit_of_measurement: '°C'
  state_topic: shellies/shellyht-E01199/sensor/temperature
- platform: mqtt
  name: greenhouse humidity
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E01199/sensor/humidity
- platform: mqtt
  name: greenhouse battery
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E01199/sensor/battery
- platform: mqtt
  name: seth bedroom temperature
  unit_of_measurement: '°C'
  state_topic: shellies/shellyht-E005D9/sensor/temperature
- platform: mqtt
  name: seth bedroom humidity
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/humidity
- platform: mqtt
  name: seth bedroom battery
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/battery
- platform: template
  sensors:
    shed_door_template:
      value_template: '{% if is_state("binary_sensor.shed_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Door'
    workshop_door_left_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_left", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door left'
    workshop_door_right_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_right", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door right'
    office_door_template:
      value_template: '{% if is_state("binary_sensor.office_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Office door right'
# power usage
- platform: mqtt
  name: currentcost power
  unit_of_measurement: 'watts'
  state_topic: currentcost/currentcost/ch1/watts
# phones
- platform: mqtt
  name: phone last incoming call
  state_topic: phonecalls/home/incoming/prefilter
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last rejected call
  state_topic: phonecalls/home/incoming/rejected
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last outgoing call
  state_topic: phonecalls/home/outgoing/dialing
  value_template: '{{ value_json.to_display }} @ {{ value_json.when }}'
# time date
- platform: time_date
  display_options:
    - "date_time"
# seth bedroom
- platform: mqtt
  name: sethbed version
  state_topic: "tractorbed/seth/version"
- platform: mqtt
  name: sethbed uptime
  state_topic: "tractorbed/seth/uptime"
  value_template: '{{ (((value | int) / 60) | int) }}'
  unit_of_measurement: hours
- platform: mqtt
  name: sethbed playing
  state_topic: "tractorbed/seth/sound/playing"
- platform: mqtt
  name: sethbed temperature
  unit_of_measurement: '°C'
  state_topic: tractorbed/seth/temperature
  value_template: '{{ ((value | float) | round(2)) }}'
- platform: mqtt
  name: sethbed humidity
  unit_of_measurement: '%'
  state_topic: tractorbed/seth/humidity
  value_template: '{{ ((value | float) | round(2)) }}'
- platform: mqtt
  name: logstore uptime
  state_topic: logstore/tele/controller/STATE
  value_template: '{{ value_json.Uptime }}'
#
- platform: mqtt
  name: starling joint balance amount
  state_topic: finance/starling/joint/balances/amount
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint balance cleared
  state_topic: finance/starling/joint/balances/clearedbalance
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint balance effective
  state_topic: finance/starling/joint/balances/effectivebalance
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint balance pending
  state_topic: finance/starling/joint/balances/pendingtransactions
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint balance available
  state_topic: finance/starling/joint/balances/availabletospend
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint balance overdraft
  state_topic: finance/starling/joint/balances/acceptedoverdraft
  unit_of_measurement: '£'
- platform: mqtt
  name: starling joint lastevent description
  state_topic: finance/starling/joint/event/description
- platform: mqtt
  name: nasdaq nflx
  state_topic: finance/stocks/nflx/ask
  unit_of_measurement: '$'
- platform: mqtt
  name: starling goal roundup
  state_topic: "finance/starling/joint/goals/Round up/saved"
  unit_of_measurement: '£'
- platform: mqtt
  name: starling goal total saved
  state_topic: "finance/starling/joint/goals/total/saved"
  unit_of_measurement: '£'
- platform: mqtt
  name: starling goal total target
  state_topic: "finance/starling/joint/goals/total/target"
  unit_of_measurement: '£'
- platform: mqtt
  name: starling goal total percentage
  state_topic: "finance/starling/joint/goals/total/percentage"
  unit_of_measurement: '%'
#
#- platform: snmp
#  name: internet uplink1 in
#  host: rt1.home.nat.ms
#  baseoid: 1.3.6.1.2.1.31.1.1.1.6.9
#  community: !secret snmp_community
#  version: '2c'
#  scan_interval: 10
#- platform: snmp
#  name: internet uplink1 out
#  host: rt1.home.nat.ms
#  baseoid: 1.3.6.1.2.1.31.1.1.1.10.9
#  community: !secret snmp_community
#  version: '2c'
#  scan_interval: 10
- platform: google_travel_time
  name: travel_time_haverfordwest
  api_key: !secret google_maps_api
  origin: Castlemorris, Haverfordwest SA62 5ES
  destination: Haverfordwest
- platform: mqtt
  name: IOController dev1 DI1
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/1/status"
- platform: mqtt
  name: IOController dev1 DI2
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/2/status"
- platform: mqtt
  name: IOController dev1 DI3
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/3/status"
- platform: mqtt
  name: IOController dev1 DI4
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/4/status"
- platform: mqtt
  name: IOController dev1 DI5
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/5/status"
- platform: mqtt
  name: IOController dev1 DI6
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/6/status"
- platform: mqtt
  name: IOController dev1 DI7
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/7/status"
- platform: mqtt
  name: IOController dev1 DI8
  state_topic: "iocontroller/dev/boards/dev1/digitalinput/8/status"
- platform: mqtt
  name: IOController dev1 connection
  state_topic: "iocontroller/dev/boards/dev1/connection"
- platform: mqtt
  name: IOController cupboard1 DI1
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/1/status"
- platform: mqtt
  name: IOController cupboard1 DI2
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/2/status"
- platform: mqtt
  name: IOController cupboard1 DI3
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/3/status"
- platform: mqtt
  name: IOController cupboard1 DI4
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/4/status"
- platform: mqtt
  name: IOController cupboard1 DI5
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/5/status"
- platform: mqtt
  name: IOController cupboard1 DI6
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/6/status"
- platform: mqtt
  name: IOController cupboard1 DI7
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/7/status"
- platform: mqtt
  name: IOController cupboard1 DI8
  state_topic: "iocontroller/home/boards/cupboard1/digitalinput/8/status"
- platform: mqtt
  name: IOController cupboard1 connection
  state_topic: "iocontroller/home/boards/cupboard1/connection"
- platform: mqtt
  name: IOController cupboard2 DI1
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/1/status"
- platform: mqtt
  name: IOController cupboard2 DI2
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/2/status"
- platform: mqtt
  name: IOController cupboard2 DI3
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/3/status"
- platform: mqtt
  name: IOController cupboard2 DI4
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/4/status"
- platform: mqtt
  name: IOController cupboard2 DI5
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/5/status"
- platform: mqtt
  name: IOController cupboard2 DI6
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/6/status"
- platform: mqtt
  name: IOController cupboard2 DI7
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/7/status"
- platform: mqtt
  name: IOController cupboard2 DI8
  state_topic: "iocontroller/home/boards/cupboard2/digitalinput/8/status"
- platform: mqtt
  name: IOController cupboard2 connection
  state_topic: "iocontroller/home/boards/cupboard2/connection"
- platform: mqtt
  name: downstairshallway temperature
  unit_of_measurement: '°C'
  state_topic: areas/downstairshallway/temperature/value
- platform: mqtt
  name: kitchen temperature
  unit_of_measurement: '°C'
  state_topic: areas/kitchen/temperature/value
- platform: mqtt
  name: lounge temperature
  unit_of_measurement: '°C'
  state_topic: areas/lounge/temperature/value
- platform: mqtt
  name: playroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/playroom/temperature/value
- platform: mqtt
  name: sauna temperature
  unit_of_measurement: '°C'
  state_topic: areas/sauna/temperature/value
- platform: mqtt
  name: utility temperature
  unit_of_measurement: '°C'
  state_topic: areas/utility/temperature/value
- platform: mqtt
  name: backbedroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/backbedroom/temperature/value
- platform: mqtt
  name: ensuite temperature
  unit_of_measurement: '°C'
  state_topic: areas/ensuite/temperature/value
- platform: mqtt
  name: mainlanding temperature
  unit_of_measurement: '°C'
  state_topic: areas/mainlanding/temperature/value
- platform: mqtt
  name: master bedroom temperature
  unit_of_measurement: '°C'
  state_topic: areas/masterbedroom/temperature/value
- platform: mqtt
  name: office temperature
  unit_of_measurement: '°C'
  state_topic: areas/office/temperature/value
- platform: mqtt
  name: office landing temperature
  unit_of_measurement: '°C'
  state_topic: areas/officelanding/temperature/value
- platform: mqtt
  name: office wc temperature
  unit_of_measurement: '°C'
  state_topic: areas/officewc/temperature/value
