- platform: yr
- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload
- platform: fastdotcom
  minute:
  - 12
  - 32
- platform: snmp
  name: Wifi clients
  host: 185.61.112.94
  baseoid: 1.3.6.1.4.1.9.9.618.1.8.12.0
  community: !secret snmp_community_readonly
  unit_of_measurement: wifi clients
- platform: mqtt
  name: pirelay1 version
  state_topic: "pirelay1/version"
- platform: mqtt
  name: pirelay2 version
  state_topic: "pirelay2/version"
- platform: mqtt
  name: pirelay3 version
  state_topic: "pirelay3/version"
- platform: mqtt
  name: bedroom master temperature
  unit_of_measurement: '°C'
  state_topic: roomsensors/bedroom-master/temperature/degrees
- platform: mqtt
  name: bedroom master humidity
  unit_of_measurement: '%'
  state_topic: roomsensors/bedroom-master/humidity/relative
- platform: template
  sensors:
    shed_door_template:
      value_template: '{% if is_state("binary_sensor.shed_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Door'
    workshop_door_left_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_left", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door left'
    workshop_door_right_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_right", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door right'
- platform: mqtt
  name: aaisp el6.a.1 sync down
  unit_of_measurement: 'Mbit/s'
  state_topic: aaisp/login/el6@a.1/syncrate/down/mb
- platform: mqtt
  name: aaisp el6.a.1 sync up
  unit_of_measurement: 'Mbit/s'
  state_topic: aaisp/login/el6@a.1/syncrate/up/mb
- platform: mqtt
  name: aaisp el6.a.2 sync down
  unit_of_measurement: 'Mbit/s'
  state_topic: aaisp/login/el6@a.2/syncrate/down/mb
- platform: mqtt
  name: aaisp el6.a.2 sync up
  unit_of_measurement: 'Mbit/s'
  state_topic: aaisp/login/el6@a.2/syncrate/up/mb
- platform: mqtt
  name: aaisp el6.a.1 quota remaining
  unit_of_measurement: 'GB'
  state_topic: aaisp/login/el6@a.1/quota/remaining/gb
- platform: mqtt
  name: aaisp el6.a.2 quota remaining
  unit_of_measurement: 'GB'
  state_topic: aaisp/login/el6@a.2/quota/remaining/gb
# evohome
- platform: mqtt
  name: heating zone house setpoint
  unit_of_measurement: '°C'
  state_topic: evohome/zone/house/setpoint
- platform: mqtt
  name: heating zone house temperature
  unit_of_measurement: '°C'
  state_topic: evohome/zone/house/temperature
- platform: mqtt
  name: heating zone office setpoint
  unit_of_measurement: '°C'
  state_topic: evohome/zone/office/setpoint
- platform: mqtt
  name: heating zone office temperature
  unit_of_measurement: '°C'
  state_topic: evohome/zone/office/temperature
- platform: mqtt
  name: heating zone nursery setpoint
  unit_of_measurement: '°C'
  state_topic: evohome/zone/nursery/setpoint
- platform: mqtt
  name: heating zone nursery temperature
  unit_of_measurement: '°C'
  state_topic: evohome/zone/nursery/temperature
- platform: mqtt
  name: heating zone master bed setpoint
  unit_of_measurement: '°C'
  state_topic: evohome/zone/master_bed/setpoint
- platform: mqtt
  name: heating zone master bed temperature
  unit_of_measurement: '°C'
  state_topic: evohome/zone/master_bed/temperature
- platform: mqtt
  name: heating zone guest bed 1 setpoint
  unit_of_measurement: '°C'
  state_topic: evohome/zone/guest_bed_1/setpoint
- platform: mqtt
  name: heating zone guest bed 1 temperature
  unit_of_measurement: '°C'
  state_topic: evohome/zone/guest_bed_1/temperature
- platform: mqtt
  name: heating hot water temperature
  unit_of_measurement: '°C'
  state_topic: evohome/hotwater/temperature
# power usage
- platform: mqtt
  name: currentcost power
  unit_of_measurement: 'watts'
  state_topic: currentcost/currentcost/ch1/watts
# phones
- platform: mqtt
  name: phone last incoming call
  state_topic: phonecalls/home/incoming/prefilter
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last rejected call
  state_topic: phonecalls/home/incoming/rejected
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last outgoing call
  state_topic: phonecalls/home/outgoing/dialing
  value_template: '{{ value_json.to_display }} @ {{ value_json.when }}'
