- platform: yr
- platform: cert_expiry
  name: "certexpiry ha.home.nat.ms"
  host: ha.home.nat.ms
- platform: cert_expiry
  name: "certexpiry llwynygorras.pbx.pembswifi.net"
  host: llwynygorras.pbx.pembswifi.net
- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload
  server_id: 16607
- platform: mqtt
  name: pirelay1 version
  state_topic: "pirelay1/version"
- platform: mqtt
  name: pirelay2 version
  state_topic: "pirelay2/version"
- platform: mqtt
  name: pirelay3 version
  state_topic: "pirelay3/version"
- platform: mqtt
  name: seth bedroom temperature
  unit_of_measurement: '°C'
  state_topic: shellies/shellyht-E005D9/sensor/temperature
- platform: mqtt
  name: seth bedroom humidity
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/humidity
- platform: mqtt
  name: seth bedroom battery
  unit_of_measurement: '%'
  state_topic: shellies/shellyht-E005D9/sensor/battery
- platform: template
  sensors:
    shed_door_template:
      value_template: '{% if is_state("binary_sensor.shed_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Door'
    workshop_door_left_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_left", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door left'
    workshop_door_right_template:
      value_template: '{% if is_state("binary_sensor.workshop_door_right", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Workshop door right'
    office_door_template:
      value_template: '{% if is_state("binary_sensor.office_door", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Office door right'
# power usage
- platform: mqtt
  name: currentcost power
  unit_of_measurement: 'watts'
  state_topic: currentcost/currentcost/ch1/watts
# phones
- platform: mqtt
  name: phone last incoming call
  state_topic: phonecalls/home/incoming/prefilter
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last rejected call
  state_topic: phonecalls/home/incoming/rejected
  value_template: '{{ value_json.from_display }} @ {{ value_json.when }}'
- platform: mqtt
  name: phone last outgoing call
  state_topic: phonecalls/home/outgoing/dialing
  value_template: '{{ value_json.to_display }} @ {{ value_json.when }}'
# time date
- platform: time_date
  display_options:
    - "date_time"
# seth bedroom
- platform: mqtt
  name: sethbed version
  state_topic: "tractorbed/seth/version"
- platform: mqtt
  name: sethbed uptime
  state_topic: "tractorbed/seth/uptime"
- platform: mqtt
  name: logstore uptime
  state_topic: logstore/tele/controller/STATE
  value_template: '{{ value_json.Uptime }}'
- platform: starlingbank
  accounts:
    - access_token: !secret starling_personal_access_token
#- platform: snmp
#  name: internet uplink1 in
#  host: rt1.home.nat.ms
#  baseoid: 1.3.6.1.2.1.31.1.1.1.6.9
#  community: !secret snmp_community
#  version: '2c'
#  scan_interval: 10
#- platform: snmp
#  name: internet uplink1 out
#  host: rt1.home.nat.ms
#  baseoid: 1.3.6.1.2.1.31.1.1.1.10.9
#  community: !secret snmp_community
#  version: '2c'
#  scan_interval: 10
- platform: google_travel_time
  name: travel_time_haverfordwest
  api_key: !secret google_maps_api
  origin: Castlemorris, Haverfordwest SA62 5ES
  destination: Haverfordwest
