- platform: mqtt
  name: "Heating hot water"
  state_topic: "heating/stat/controller/POWER1"
  command_topic: "heating/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Heating central heating"
  state_topic: "heating/stat/controller/POWER2"
  command_topic: "heating/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Patio fountain"
  state_topic: "patio/stat/controller/POWER1"
  command_topic: "patio/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Patio festoon"
  state_topic: "patio/stat/controller/POWER2"
  command_topic: "patio/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Logstore outside"
  state_topic: "logstore/stat/controller/POWER1"
  command_topic: "logstore/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true


- platform: mqtt
  name: "Logstore porch"
  state_topic: "logstore/stat/controller/POWER2"
  command_topic: "logstore/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Logstore indoor"
  state_topic: "logstore/stat/controller/POWER3"
  command_topic: "logstore/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Bridge spotlights"
  state_topic: "greenhouse/stat/controller/POWER1"
  command_topic: "greenhouse/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A1"
  state_topic: "irrigation1/stat/controller/POWER1"
  command_topic: "irrigation1/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A2"
  state_topic: "irrigation1/stat/controller/POWER2"
  command_topic: "irrigation1/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A3"
  state_topic: "irrigation1/stat/controller/POWER3"
  command_topic: "irrigation1/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A4"
  state_topic: "irrigation1/stat/controller/POWER4"
  command_topic: "irrigation1/cmnd/controller/POWER4"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B1"
  state_topic: "irrigation2/stat/controller/POWER1"
  command_topic: "irrigation2/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B2"
  state_topic: "irrigation2/stat/controller/POWER2"
  command_topic: "irrigation2/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B3"
  state_topic: "irrigation2/stat/controller/POWER3"
  command_topic: "irrigation2/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B4"
  state_topic: "irrigation2/stat/controller/POWER4"
  command_topic: "irrigation2/cmnd/controller/POWER4"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Office light"
  state_topic: "shelly1/office/stat/controller/POWER"
  command_topic: "shelly1/office/cmnd/controller/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Downstairs WC"
  state_topic: "shelly1/downstairswc/stat/controller/POWER"
  command_topic: "shelly1/downstairswc/cmnd/controller/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
