- platform: mqtt
  name: "Heating hot water"
  state_topic: "heating/stat/controller/POWER1"
  command_topic: "heating/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Heating central heating"
  state_topic: "heating/stat/controller/POWER2"
  command_topic: "heating/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Heating hot water immersion"
  state_topic: "heating/stat/controller/POWER3"
  command_topic: "heating/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Patio fountain"
  state_topic: "patio/stat/controller/POWER1"
  command_topic: "patio/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Patio festoon"
  state_topic: "patio/stat/controller/POWER2"
  command_topic: "patio/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Logstore outside"
  state_topic: "logstore/stat/controller/POWER1"
  command_topic: "logstore/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true


- platform: mqtt
  name: "Logstore porch"
  state_topic: "logstore/stat/controller/POWER2"
  command_topic: "logstore/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Logstore indoor"
  state_topic: "logstore/stat/controller/POWER3"
  command_topic: "logstore/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Bridge spotlights"
  state_topic: "greenhouse/stat/controller/POWER1"
  command_topic: "greenhouse/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A1"
  state_topic: "irrigation1/stat/controller/POWER1"
  command_topic: "irrigation1/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A2"
  state_topic: "irrigation1/stat/controller/POWER2"
  command_topic: "irrigation1/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A3"
  state_topic: "irrigation1/stat/controller/POWER3"
  command_topic: "irrigation1/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation A4"
  state_topic: "irrigation1/stat/controller/POWER4"
  command_topic: "irrigation1/cmnd/controller/POWER4"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B1"
  state_topic: "irrigation2/stat/controller/POWER1"
  command_topic: "irrigation2/cmnd/controller/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B2"
  state_topic: "irrigation2/stat/controller/POWER2"
  command_topic: "irrigation2/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B3"
  state_topic: "irrigation2/stat/controller/POWER3"
  command_topic: "irrigation2/cmnd/controller/POWER3"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Irrigation B4"
  state_topic: "irrigation2/stat/controller/POWER4"
  command_topic: "irrigation2/cmnd/controller/POWER4"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Office light"
  state_topic: "shelly1/office/stat/controller/POWER"
  command_topic: "shelly1/office/cmnd/controller/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Downstairs WC"
  state_topic: "shelly1/downstairswc/stat/controller/POWER"
  command_topic: "shelly1/downstairswc/cmnd/controller/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Sethbed local control"
  state_topic: "tractorbed/seth/service/stat/localcontrol"
  command_topic: "tractorbed/seth/service/cmnd/localcontrol"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output LED power"
  state_topic: "tractorbed/seth/outputs/stat/ledpower"
  command_topic: "tractorbed/seth/outputs/cmnd/ledpower"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output LED 1"
  state_topic: "tractorbed/seth/outputs/stat/led1"
  command_topic: "tractorbed/seth/outputs/cmnd/led1"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output LED 2"
  state_topic: "tractorbed/seth/outputs/stat/led2"
  command_topic: "tractorbed/seth/outputs/cmnd/led2"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output LED 3"
  state_topic: "tractorbed/seth/outputs/stat/led3"
  command_topic: "tractorbed/seth/outputs/cmnd/led3"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 1"
  state_topic: "tractorbed/seth/outputs/stat/relay1"
  command_topic: "tractorbed/seth/outputs/cmnd/relay1"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 2"
  state_topic: "tractorbed/seth/outputs/stat/relay2"
  command_topic: "tractorbed/seth/outputs/cmnd/relay2"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 3"
  state_topic: "tractorbed/seth/outputs/stat/relay3"
  command_topic: "tractorbed/seth/outputs/cmnd/relay3"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 4"
  state_topic: "tractorbed/seth/outputs/stat/relay4"
  command_topic: "tractorbed/seth/outputs/cmnd/relay4"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 5"
  state_topic: "tractorbed/seth/outputs/stat/relay5"
  command_topic: "tractorbed/seth/outputs/cmnd/relay5"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 6"
  state_topic: "tractorbed/seth/outputs/stat/relay6"
  command_topic: "tractorbed/seth/outputs/cmnd/relay6"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 7"
  state_topic: "tractorbed/seth/outputs/stat/relay7"
  command_topic: "tractorbed/seth/outputs/cmnd/relay7"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Sethbed output Relay 8"
  state_topic: "tractorbed/seth/outputs/stat/relay8"
  command_topic: "tractorbed/seth/outputs/cmnd/relay8"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "IOController dev1 DO1"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/1/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/1/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO2"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/2/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/2/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO3"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/3/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/3/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO4"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/4/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/4/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO5"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/5/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/5/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO6"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/6/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/6/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO7"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/7/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/7/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "IOController dev1 DO8"
  state_topic: "iocontroller/dev/boards/dev1/digitaloutput/8/status"
  command_topic: "iocontroller/dev/boards/dev1/digitaloutput/8/command"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
