- platform: tplink
  host: 193.47.147.208
  name: Hair Straightners

- platform: tplink
  host: 193.47.147.211
  name: Bridge lights

- platform: tplink
  host: 193.47.147.215
  name: Lounge lamp

- platform: tplink
  host: 193.47.147.213
  name: Temp1

- platform: mqtt
  name: "Heating hot water"
  state_topic: "heating/stat/controller/POWER1"
  command_topic: "heating/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Heating central heating"
  state_topic: "heating/stat/controller/POWER2"
  command_topic: "heating/cmnd/controller/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
